import { Layout } from "@/components/Layout";
import { Typography } from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";

export default function Home() {
  return (
    <Layout>
      <Grid>
        <Typography color="text">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam orci diam, faucibus et ante sed, scelerisque lacinia neque. Nullam sit amet erat ut augue convallis finibus non ut dui. Aenean quis tempus eros. Nulla facilisis fringilla mi, at faucibus mi porta in. Sed pharetra mi aliquam, convallis elit nec, ullamcorper erat. Suspendisse a elit enim. Morbi eros sapien, ultricies eget ante et, accumsan laoreet purus. Morbi ante ipsum, suscipit vel imperdiet efficitur, posuere porta libero. Morbi mattis id odio vitae laoreet. Vestibulum sed imperdiet odio. Quisque urna urna, pulvinar ac nibh nec, pretium sodales massa. Curabitur quis purus et eros placerat varius ut laoreet tortor. Maecenas fringilla convallis tellus eu luctus. Quisque egestas est arcu, in ornare odio mollis sit amet. Phasellus dolor elit, cursus non sem vitae, condimentum sodales odio.
          <br />
          Sed ornare fermentum nisi, convallis venenatis nunc semper finibus. Praesent quis lectus ipsum. Fusce in velit ligula. Cras sed dapibus lectus, placerat rhoncus mi. Vivamus sit amet mollis lectus. Ut tellus libero, aliquet vitae leo nec, accumsan tristique libero. Ut aliquet sed metus scelerisque dapibus. Mauris scelerisque tincidunt felis. Mauris bibendum mattis metus, ac sollicitudin nisi vulputate id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc at velit sagittis, pulvinar metus tincidunt, fringilla odio. Sed non diam sed nunc venenatis vehicula eget et ex.
          <br />
          Etiam fringilla bibendum commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla fermentum mauris vitae mi sodales malesuada. Aliquam sit amet urna cursus, elementum quam sit amet, congue nibh. Sed ultricies nulla dignissim accumsan auctor. Fusce at erat mattis, bibendum orci vel, sollicitudin arcu. Vivamus lacinia sapien elit, in dignissim tortor aliquam eu. Aenean pulvinar, nunc id interdum elementum, tortor orci finibus elit, sit amet blandit nisl erat ut justo. Morbi vestibulum justo vel egestas viverra. Proin in viverra magna, eget bibendum massa. Fusce pretium ante nec odio cursus, non aliquam turpis fringilla. Morbi consectetur gravida neque non ornare.
          <br />
          Proin laoreet ex sed consequat efficitur. Curabitur libero nunc, bibendum non rutrum sed, auctor tincidunt massa. Phasellus volutpat posuere leo tincidunt varius. Nam felis lorem, ornare ac ante id, dapibus dignissim risus. Donec ac metus lectus. Proin eu elementum dui. Quisque pulvinar justo neque, eu consequat sapien viverra at. Mauris vitae volutpat mauris, ut faucibus ante. Quisque ut lacus nec dolor consequat gravida sit amet vitae magna. Pellentesque tristique nibh odio, in egestas lacus vehicula tempus. Praesent ut magna mattis, fermentum erat eget, feugiat metus. Aenean vulputate vehicula turpis, a fringilla nibh tincidunt in. Suspendisse et risus risus.
          <br />
          In hac habitasse platea dictumst. Phasellus odio erat, egestas sed varius scelerisque, volutpat at odio. Vivamus bibendum fringilla orci nec dignissim. Suspendisse placerat viverra nisl, a faucibus nunc consequat quis. Fusce tempus risus a nunc gravida blandit. Donec eu blandit dui. Etiam sem metus, sagittis eget lacus vel, malesuada elementum massa. Suspendisse lacinia magna sit amet nunc convallis, suscipit pharetra purus accumsan.

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam orci diam, faucibus et ante sed, scelerisque lacinia neque. Nullam sit amet erat ut augue convallis finibus non ut dui. Aenean quis tempus eros. Nulla facilisis fringilla mi, at faucibus mi porta in. Sed pharetra mi aliquam, convallis elit nec, ullamcorper erat. Suspendisse a elit enim. Morbi eros sapien, ultricies eget ante et, accumsan laoreet purus. Morbi ante ipsum, suscipit vel imperdiet efficitur, posuere porta libero. Morbi mattis id odio vitae laoreet. Vestibulum sed imperdiet odio. Quisque urna urna, pulvinar ac nibh nec, pretium sodales massa. Curabitur quis purus et eros placerat varius ut laoreet tortor. Maecenas fringilla convallis tellus eu luctus. Quisque egestas est arcu, in ornare odio mollis sit amet. Phasellus dolor elit, cursus non sem vitae, condimentum sodales odio.
          <br />
          Sed ornare fermentum nisi, convallis venenatis nunc semper finibus. Praesent quis lectus ipsum. Fusce in velit ligula. Cras sed dapibus lectus, placerat rhoncus mi. Vivamus sit amet mollis lectus. Ut tellus libero, aliquet vitae leo nec, accumsan tristique libero. Ut aliquet sed metus scelerisque dapibus. Mauris scelerisque tincidunt felis. Mauris bibendum mattis metus, ac sollicitudin nisi vulputate id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc at velit sagittis, pulvinar metus tincidunt, fringilla odio. Sed non diam sed nunc venenatis vehicula eget et ex.
          <br />
          Etiam fringilla bibendum commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla fermentum mauris vitae mi sodales malesuada. Aliquam sit amet urna cursus, elementum quam sit amet, congue nibh. Sed ultricies nulla dignissim accumsan auctor. Fusce at erat mattis, bibendum orci vel, sollicitudin arcu. Vivamus lacinia sapien elit, in dignissim tortor aliquam eu. Aenean pulvinar, nunc id interdum elementum, tortor orci finibus elit, sit amet blandit nisl erat ut justo. Morbi vestibulum justo vel egestas viverra. Proin in viverra magna, eget bibendum massa. Fusce pretium ante nec odio cursus, non aliquam turpis fringilla. Morbi consectetur gravida neque non ornare.
          <br />
          Proin laoreet ex sed consequat efficitur. Curabitur libero nunc, bibendum non rutrum sed, auctor tincidunt massa. Phasellus volutpat posuere leo tincidunt varius. Nam felis lorem, ornare ac ante id, dapibus dignissim risus. Donec ac metus lectus. Proin eu elementum dui. Quisque pulvinar justo neque, eu consequat sapien viverra at. Mauris vitae volutpat mauris, ut faucibus ante. Quisque ut lacus nec dolor consequat gravida sit amet vitae magna. Pellentesque tristique nibh odio, in egestas lacus vehicula tempus. Praesent ut magna mattis, fermentum erat eget, feugiat metus. Aenean vulputate vehicula turpis, a fringilla nibh tincidunt in. Suspendisse et risus risus.
          <br />
          In hac habitasse platea dictumst. Phasellus odio erat, egestas sed varius scelerisque, volutpat at odio. Vivamus bibendum fringilla orci nec dignissim. Suspendisse placerat viverra nisl, a faucibus nunc consequat quis. Fusce tempus risus a nunc gravida blandit. Donec eu blandit dui. Etiam sem metus, sagittis eget lacus vel, malesuada elementum massa. Suspendisse lacinia magna sit amet nunc convallis, suscipit pharetra purus accumsan.
        </Typography>
      </Grid>
    </Layout>
  );
}
